licensing.build.dir=${licensing.dir}/build
licensing.build.web.dir=${licensing.build.dir}/web
licensing.build.classes.dir=${licensing.build.web.dir}/WEB-INF/classes
licensing.build.meta.inf.dir=${licensing.build.web.dir}/META-INF
licensing.build.test.dir=${licensing.build.dir}/test

licensing.jar.compress=true
licensing.dist.dir=${licensing.dir}/dist
licensing.war.name=licensing.war
licensing.dist.war=${licensing.dist.dir}/${licensing.war.name}

licensing.src.dir=${licensing.dir}/src
licensing.web.dir=${licensing.dir}/web
licensing.conf.dir=${licensing.dir}/conf

licensing.test.dir=${licensing.dir}/test
licensing.test.results.dir=${licensing.build.test.dir}/results
licensing.test.htmlresults.dir=${licensing.test.results.dir}/html

licensing.hibernate.cfg.xml=${licensing.web.dir}/WEB-INF/hibernate.cfg.xml

licensing.sql.test_data=${licensing.dir}/sql/test_data.sql

licensing.javac.classpath=\
    ${file.reference.spring-2.5.2.jar}:\
    ${file.reference.spring-webmvc-2.5.2.jar}:\
    ${file.reference.servlet-api.jar}:\
    ${file.reference.commons-logging-1.1.jar}:\
    ${file.reference.ejb3-persistence-3.3.1.jar}:\
    ${file.reference.jaxrpc-1.1.jar}:\
    ${file.reference.hibernate-annotations-3.3.1.jar}:\
    ${file.reference.hibernate-commons-annotations-3.3.1.jar}:\
    ${file.reference.hibernate-3.2.6.jar}:\
    ${file.reference.axis-1.4.jar}:\
    ${file.reference.commons-codec-1.3.jar}:\
    ${file.reference.icu4j-3.8-transliterator.jar}:\
    ${file.reference.jsp-api.jar}:\
    ${file.reference.displaytag-1.1.1.jar}:\
    ${file.reference.jcommon-1.0.12.jar}:\
    ${file.reference.postgresql-8.3-603.jdbc3.jar}

licensing.javac.test.classpath=\
    ${file.reference.junit-3.8.1.jar}:\
    ${file.reference.spring-test-2.5.1.jar}

licensing.hibernatetool.classpath=\
    ${file.reference.hibernate-tools.jar}:\
    ${file.reference.hibernate-3.2.6.jar}:\
    ${file.reference.hibernate-annotations-3.3.1.jar}:\
    ${file.reference.hibernate-commons-annotations-3.3.1.jar}:\
    ${file.reference.commons-logging-1.1.jar}:\
    ${file.reference.dom4j-1.6.1.jar}:\
    ${file.reference.ejb3-persistence-3.3.1.jar}:\
    ${file.reference.commons-collections-3.2.jar}:\
    ${file.reference.ojdbc14.jar}:\
    ${file.reference.postgresql-8.3-603.jdbc3.jar}
