log4j.rootLogger=INFO, stdout, smtplog

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %p [%c] - %m%n

log4j.appender.smtplog=org.apache.log4j.net.SMTPAppender
log4j.appender.smtplog.Threshold=ERROR
log4j.appender.smtplog.SMTPHost=vs109.server4u.cz
log4j.appender.smtplog.To=info@edhouse.cz
log4j.appender.smtplog.From=info@edhouse.cz
log4j.appender.smtplog.Subject=Licensing [log4j]
log4j.appender.smtplog.BufferSize=10
log4j.appender.smtplog.layout=org.apache.log4j.PatternLayout
log4j.appender.smtplog.layout.ConversionPattern=%d %p [%c] - %m%n
